management:
  security:  
   enabled: false      
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
    
server:
    port: 3000
    
spring:
  application:
    name: authserver
    profiles:
    active:
      default  

  cloud:
    config:
       name: authserver
       uri: http://localhost:8888
    discovery:
       service-id: config
       enabled: true
  data:
    mongodb:    
      uri: mongodb://localhost:27017/socnet    

jwt:
    header: Authorization
    expires_in: 600  
    mobile_expires_in: 600    
    secret: ap163#$96@
    
hystrix:
  command:
    RemoteMessageClientCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    RemoteMessageAnnotationClient:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000      


eureka:
  instance:  
    leaseRenewalIntervalInSeconds: 10
  client:
    enabled: true
    registryFetchIntervalSeconds: 5 
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}