spring:
  application:
    name: eureka

security:
  basic:
    enabled: false
#  user:
#      name: user 
#      password: password  
#    
    
server: 
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    health-check-url-path: /actuator/health
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 3   
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://localhost:8761